services:
  frame-compare:
    profiles:
      - gpu-nvidia
    environment:
      - VAPOURSYNTH_EXTRA_PLUGIN_PATH=/opt/vapoursynth-extra-plugins
      - LIBGL_ALWAYS_SOFTWARE=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    gpus: all

  frame-compare-test:
    profiles:
      - gpu-nvidia
    environment:
      - VAPOURSYNTH_EXTRA_PLUGIN_PATH=/opt/vapoursynth-extra-plugins
      - LIBGL_ALWAYS_SOFTWARE=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    gpus: all

  frame-compare-run:
    profiles:
      - gpu-nvidia
    environment:
      - VAPOURSYNTH_EXTRA_PLUGIN_PATH=/opt/vapoursynth-extra-plugins
      - LIBGL_ALWAYS_SOFTWARE=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    gpus: all
