from typing import Any


class Console:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def print(self, *objects: Any, **kwargs: Any) -> None: ...
    def rule(self, title: str | None = ..., **kwargs: Any) -> None: ...
