from typing import Any, Protocol


class Task:
    id: int


class ProgressColumn:
    ...


class TextColumn(ProgressColumn):
    def __init__(self, text_format: str, *args: Any, **kwargs: Any) -> None: ...


class BarColumn(ProgressColumn):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class Progress:
    def __init__(self, *columns: ProgressColumn, **kwargs: Any) -> None: ...
    def add_task(self, description: str, *args: Any, **kwargs: Any) -> Task: ...
    def update(self, task_id: int, advance: float | None = ..., description: str | None = ...) -> None: ...
    def refresh(self) -> None: ...
    def stop(self) -> None: ...
    def __enter__(self) -> "Progress": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> None: ...
