from typing import Any


class Text:
    def __init__(self, text: str = ..., *args: Any, **kwargs: Any) -> None: ...
    def append(self, text: str, *args: Any, **kwargs: Any) -> "Text": ...
    def stylize(self, *args: Any, **kwargs: Any) -> None: ...
