"""Auto-generated from contracts/cli_flags.yaml — DO NOT EDIT MANUALLY.

Regenerate with: python scripts/generate_contract_views.py
"""

from __future__ import annotations

from typing import TypedDict


class CLIFlagInfo(TypedDict):
    """Type-safe CLI flag metadata."""
    long: str
    short: str | None
    type: str
    default: bool | str | int | None
    config_key: str | None
    help: str
    choices: list[str] | None
    envvar: str | None


CLI_FLAGS: dict[str, CLIFlagInfo] = {
    "FLAG_ROOT": {
        "long": "--root",
        "short": "-r",
        "type": "Path",
        "default": ".",
        "config_key": None,
        "help": "Workspace root directory",
        "choices": None,
        "envvar": "FRAME_COMPARE_ROOT",
    },
    "FLAG_CONFIG": {
        "long": "--config",
        "short": "-c",
        "type": "Path",
        "default": None,
        "config_key": None,
        "help": "Config file path",
        "choices": None,
        "envvar": "FRAME_COMPARE_CONFIG",
    },
    "FLAG_INPUT": {
        "long": "--input",
        "short": "-i",
        "type": "Path",
        "default": None,
        "config_key": "paths.input_dir",
        "help": "Input directory override",
        "choices": None,
        "envvar": None,
    },
    "FLAG_TM_PRESET": {
        "long": "--tm-preset",
        "short": "-p",
        "type": "str",
        "default": None,
        "config_key": "color.preset",
        "help": "Tonemap preset (defers to config)",
        "choices": ["reference", "filmic", "contrast", "bt2390_spec", "spline", "bright_lift", "highlight_guard"],
        "envvar": None,
    },
    "FLAG_TM_TARGET": {
        "long": "--tm-target",
        "short": "-t",
        "type": "int",
        "default": None,
        "config_key": "color.target_nits",
        "help": "Target peak luminance (defers to config)",
        "choices": None,
        "envvar": None,
    },
    "FLAG_TM_CURVE": {
        "long": "--tm-curve",
        "short": None,
        "type": "str",
        "default": None,
        "config_key": "color.tone_curve",
        "help": "Tone curve override",
        "choices": ["bt2390", "spline", "reinhard", "mobius", "linear"],
        "envvar": None,
    },
    "FLAG_FRAME_COUNT": {
        "long": "--frame-count",
        "short": "-n",
        "type": "int",
        "default": None,
        "config_key": "analysis.frame_count",
        "help": "Frames to capture (defers to config)",
        "choices": None,
        "envvar": None,
    },
    "FLAG_SEED": {
        "long": "--seed",
        "short": "-s",
        "type": "int",
        "default": None,
        "config_key": "analysis.random_seed",
        "help": "Random seed",
        "choices": None,
        "envvar": None,
    },
    "FLAG_SKIP_ANALYSIS": {
        "long": "--skip-analysis",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Skip frame analysis; use uniform frame sampling with seed",
        "choices": None,
        "envvar": None,
    },
    "FLAG_OVERLAY": {
        "long": "--overlay",
        "short": None,
        "type": "str",
        "default": None,
        "config_key": "screenshots.overlay_mode",
        "help": "Overlay mode (defers to config)",
        "choices": ["minimal", "standard", "diagnostic", "none"],
        "envvar": None,
    },
    "FLAG_NO_UPLOAD": {
        "long": "--no-upload",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": "slowpics.auto_upload",
        "help": "Skip slow.pics upload",
        "choices": None,
        "envvar": None,
    },
    "FLAG_NO_CACHE": {
        "long": "--no-cache",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Ignore cached metrics",
        "choices": None,
        "envvar": None,
    },
    "FLAG_FROM_CACHE_ONLY": {
        "long": "--from-cache-only",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Use only cached snapshot",
        "choices": None,
        "envvar": None,
    },
    "FLAG_WRITE_CONFIG": {
        "long": "--write-config",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Write resolved config and exit",
        "choices": None,
        "envvar": None,
    },
    "FLAG_DIAGNOSE_PATHS": {
        "long": "--diagnose-paths",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Print path diagnostics as JSON",
        "choices": None,
        "envvar": None,
    },
    "FLAG_QUIET": {
        "long": "--quiet",
        "short": "-q",
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Suppress output",
        "choices": None,
        "envvar": None,
    },
    "FLAG_VERBOSE": {
        "long": "--verbose",
        "short": "-v",
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Debug output",
        "choices": None,
        "envvar": None,
    },
    "FLAG_JSON": {
        "long": "--json",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "JSON output mode",
        "choices": None,
        "envvar": None,
    },
    "FLAG_NO_COLOR": {
        "long": "--no-color",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Disable colors",
        "choices": None,
        "envvar": None,
    },
    "FLAG_SKIP_METADATA": {
        "long": "--skip-metadata",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Skip TMDB metadata lookup",
        "choices": None,
        "envvar": None,
    },
    "FLAG_SKIP_DOVI": {
        "long": "--skip-dovi",
        "short": None,
        "type": "bool",
        "default": False,
        "config_key": None,
        "help": "Skip Dolby Vision extraction",
        "choices": None,
        "envvar": None,
    },
}
