from typing import Any


class MonkeyPatch:
    def setattr(self, target: object, name: str, value: object) -> None: ...
    def delattr(self, target: object, name: str) -> None: ...
    def setenv(self, name: str, value: str, *, prepend: bool = ...) -> None: ...
    def getenv(self, name: str, default: str | None = ...) -> str | None: ...
    def undo(self) -> None: ...
