"""Markdown rendering for generated API docs."""

from __future__ import annotations

import ast
from pathlib import Path

from api_docs.model import (
    LOCKED_MODULES,
    ModuleInfo,
    ResolvedSymbol,
    alias_target_for_export,
    first_paragraph,
    load_module_info,
    resolve_symbol,
)


def generate_markdown(
    *,
    project_root: Path,
    module_cache: dict[Path, ModuleInfo],
) -> tuple[str, list[str]]:
    missing_docstrings: list[str] = []
    out_lines: list[str] = [
        "# API Reference",
        "",
        "> Generated by `scripts/generate_api_docs.py`. Do not edit manually.",
        "",
    ]

    for module_name, rel_path in LOCKED_MODULES:
        module_path = (project_root / rel_path).resolve()
        module = module_cache.get(module_path)
        if module is None:
            module = load_module_info(module_name, module_path, require_dunder_all=True)
            module_cache[module_path] = module

        _append_module_markdown(
            out_lines=out_lines,
            missing_docstrings=missing_docstrings,
            project_root=project_root,
            module_cache=module_cache,
            module=module,
        )

    return "\n".join(out_lines).rstrip() + "\n", missing_docstrings


def _append_module_markdown(
    *,
    out_lines: list[str],
    missing_docstrings: list[str],
    project_root: Path,
    module_cache: dict[Path, ModuleInfo],
    module: ModuleInfo,
) -> None:
    out_lines.append(f"## {module.module_name}")
    out_lines.append("")
    if module.module_doc:
        out_lines.append(module.module_doc)
        out_lines.append("")

    for export in sorted(module.exports, key=lambda s: (s.lower(), s)):
        resolved = resolve_symbol(
            project_root=project_root,
            module=module,
            name=export,
            module_cache=module_cache,
            visited=set(),
        )
        _append_export_markdown(
            out_lines=out_lines,
            missing_docstrings=missing_docstrings,
            export=export,
            resolved=resolved,
            alias_target=alias_target_for_export(export, module.symbols.get(export)),
        )


def _append_export_markdown(
    *,
    out_lines: list[str],
    missing_docstrings: list[str],
    export: str,
    resolved: ResolvedSymbol,
    alias_target: str | None,
) -> None:
    out_lines.append(f"### {export}")
    out_lines.append("")

    if resolved.kind == "function":
        _append_function_markdown(
            out_lines=out_lines,
            missing_docstrings=missing_docstrings,
            export=export,
            resolved=resolved,
            alias_target=alias_target,
        )
        return
    if resolved.kind == "class":
        _append_class_markdown(
            out_lines=out_lines,
            missing_docstrings=missing_docstrings,
            export=export,
            resolved=resolved,
        )
        return
    if resolved.kind == "constant":
        _append_constant_markdown(out_lines=out_lines, export=export, resolved=resolved)
        return
    raise ValueError(f"unsupported resolved kind for {export}: {resolved.kind}")


def _append_function_markdown(
    *,
    out_lines: list[str],
    missing_docstrings: list[str],
    export: str,
    resolved: ResolvedSymbol,
    alias_target: str | None,
) -> None:
    if not isinstance(resolved.node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        raise ValueError(f"resolved function has unexpected node for {export}")

    signature = _render_signature(resolved.node)
    if signature.startswith(f"{resolved.node.name}(") and export != resolved.node.name:
        signature = signature.replace(f"{resolved.node.name}(", f"{export}(", 1)
    out_lines.append(f"`{signature}`")
    out_lines.append("")
    if alias_target is not None:
        out_lines.append(f"Alias of `{alias_target}`.")
        out_lines.append("")
        return

    doc = first_paragraph(ast.get_docstring(resolved.node) or "")
    if not doc:
        missing_docstrings.append(export)
        return
    out_lines.append(doc)
    out_lines.append("")


def _append_class_markdown(
    *,
    out_lines: list[str],
    missing_docstrings: list[str],
    export: str,
    resolved: ResolvedSymbol,
) -> None:
    if not isinstance(resolved.node, ast.ClassDef):
        raise ValueError(f"resolved class has unexpected node for {export}")

    out_lines.append(f"`{export}`")
    out_lines.append("")
    doc = first_paragraph(ast.get_docstring(resolved.node) or "")
    if not doc:
        missing_docstrings.append(export)
        return
    out_lines.append(doc)
    out_lines.append("")


def _append_constant_markdown(
    *,
    out_lines: list[str],
    export: str,
    resolved: ResolvedSymbol,
) -> None:
    if not isinstance(resolved.node, (ast.Assign, ast.AnnAssign)):
        raise ValueError(f"resolved constant has unexpected node for {export}")

    out_lines.append(f"`{export}` — constant ({_constant_type(resolved.node)})")
    out_lines.append("")


def _render_arg(arg: ast.arg, default: ast.expr | None) -> str:
    rendered = arg.arg
    if arg.annotation is not None:
        rendered += f": {ast.unparse(arg.annotation)}"
    if default is not None:
        rendered += f" = {ast.unparse(default)}"
    return rendered


def _render_signature(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = fn.args
    pos_args = list(args.posonlyargs) + list(args.args)
    pos_defaults = [None] * (len(pos_args) - len(args.defaults)) + list(args.defaults)
    rendered_parts: list[str] = []

    for i, (arg, default) in enumerate(zip(pos_args, pos_defaults, strict=True)):
        rendered_parts.append(_render_arg(arg, default))
        if args.posonlyargs and i == len(args.posonlyargs) - 1:
            rendered_parts.append("/")

    if args.vararg is not None:
        rendered_parts.append(f"*{args.vararg.arg}")
    elif args.kwonlyargs:
        rendered_parts.append("*")

    for arg, default in zip(args.kwonlyargs, args.kw_defaults, strict=True):
        rendered_parts.append(_render_arg(arg, default))

    if args.kwarg is not None:
        rendered_parts.append(f"**{args.kwarg.arg}")

    ret = ast.unparse(fn.returns) if fn.returns is not None else "None"
    return f"{fn.name}({', '.join(rendered_parts)}) -> {ret}"


def _constant_type(assign: ast.Assign | ast.AnnAssign) -> str:
    value = assign.value
    if value is None:
        return "unknown"
    if isinstance(value, ast.Dict):
        return "dict"
    if isinstance(value, ast.List):
        return "list"
    if isinstance(value, ast.Tuple):
        return "tuple"
    if isinstance(value, ast.Set):
        return "set"
    if not isinstance(value, ast.Constant):
        return "unknown"
    constant_value = value.value
    if constant_value is None:
        return "None"
    return type(constant_value).__name__
